layout_spectrum: 0.7045646980404854
typography_spectrum: 0.4112145744729787
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6675431444309652
  lightness: 0.01852459693327546
  saturation: 0.1744479986373335
  rhythmicContrast: 0.130830419017002
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Shawn McCool
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ShawnMc.Cool
description: 'software, business, and game design'
purpose: []
