name: ShawnMcCool
favicon: null
layout_spectrum: 0.15801227814517915
typography_spectrum: 0.8913367523346096
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.6675431444309652
  lightness: 0.01852459693327546
  saturation: 0.1744479986373335
  rhythmicContrast: 0.130830419017002
purpose: []
